CREATE TABLE JobPostings (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Title NVARCHAR(100) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	Location NVARCHAR(MAX) NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

SELECT * FROM JobPostings;
